version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-14
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql:ro
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    environment:
      - POSTGRES_DB=best_travel_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    container_name: redis-6
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}

  mongo:
    image: mongo:5.0.6
    container_name: mongo-5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: best_travel_db
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"